name: compile_site

on:
  push:
    paths:
      - 'guides/*.md'
      - 'datasets/*.md'
      - 'tools/*.md'
      - 'workflows/*.yml'
    branches:
      - main

env:
  remote: 'Innovation-Information-Initiative/Open-Innovation-Dataset-Index'
  branch: main
jobs:
  submit:
    runs-on: ubuntu-latest
    name: Take added markdown files and compose into site
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"


      - name: Copy files to site and add layout
        env: 
          # need to read in as string; GA doesn't support array assignment
          INPUT_FOLDERS: "guides;datasets;tools"
        run: |
            IFS=';' read -ra input_array <<< "${{ env.INPUT_FOLDERS }}"
            for dir in "${input_array[@]}"; do
              cp -r ${dir}/* app/src/index/_${dir}/
              for file in app/src/index/_${dir}/*.md; do
                sed -i 's/shortname:/slug:/g;' $file
              done
            done


      - name: Commit files
        run: |
            git pull
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add app/**.md
            git commit -m "compiled site after edit to markdown files"
            git push

