name: Process Google Sheet Edits

on:
  # edit site using webhook
  repository_dispatch:
    types: [update_relationship]

env:
  remote: 'Innovation-Information-Initiative/Open-Innovation-Dataset-Index'
  branch: main

jobs:
  update_sheet:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.16

      - name: set up Python environment
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -v gspread==4.0.1
          python3 -m pip install gspread_dataframe
          python3 -m pip install pandas
          python3 -m pip install furl
          python3 -m pip install Pillow
          python3 -m pip install python-frontmatter
          python3 -m pip install six

      - name: update relationship
        id: 'sheet_to_csv'
        env: 
          INPUT_CREDS: ${{ secrets.GSHEET_CREDENTIALS }}
          INPUT_TEMPDIR: 'index_archive'
          INPUT_SHEET_ID: '1bdyhGrj0oNz-_qW3Rv2GNGqhZZ73rgj-DYWePLA_1Ms'
          rship: |
            { 
              "uuid": "${{ github.event.client_payload.rship.uuid }}", 
              "shortname": "${{ github.event.client_payload.rship.shortname }}", 
              "relationship_type": "${{ github.event.client_payload.rship.relationship_type }}"
            }
        run: >
          python3 scripts/update_gsheet.py
          ${{ github.event.client_payload.uuid }}
          "related_projects"
