name: index_archive

on:
  schedule:
  - cron: "0 0 * * *"
env:
  id: '1bdyhGrj0oNz-_qW3Rv2GNGqhZZ73rgj-DYWePLA_1Ms'
  remote: 'Innovation-Information-Initiative/Dataset-Index-Sheet-Tracker'
  branch: main
jobs:
  pull_sheet:
    runs-on: ubuntu-latest
    name: Pulling regular updates from the I3 Essential Patent Datasets sheet
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: set up Python environment
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install gspread

      - name: Pull GSheet data
        id: 'sheet_to_csv'
        env: 
          INPUT_CREDS: ${{ secrets.GSHEET_CREDENTIALS }}
          INPUT_SHEETS: |
            [
              { "id": "${{ env.id }}", "title": "Open_Patent_Datasets" },
              { "id": "${{ env.id }}", "title": "Data_Publishing_Platform_Guide" }
            ]
          INPUT_TEMPDIR: 'index_archive'
        run: python3 pull_sheet.py

      - name: commit files
        run: |
            git pull
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "generated files based on google sheet"
            git push
