name: submit_dataset

on:
  pull_request_target:
    types: [opened, reopened, edited]
    paths:
    - 'datasets/**.md'

env:
  id: '1bdyhGrj0oNz-_qW3Rv2GNGqhZZ73rgj-DYWePLA_1Ms'
  remote: 'Innovation-Information-Initiative/Dataset-Index-Sheet-Tracker'
  branch: main
jobs:
  submit:
    runs-on: ubuntu-latest
    name: Handling additions and edits to the dataset index
    steps:

      - name: get PR branch
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
          ssh-key: "${{ secrets.COMMIT_KEY }}"

      - name: Fetch
        run: |
          git fetch origin pull/${{ github.event.number }}/head:${{ env.BRANCH_NAME }}
          git checkout ${{ env.BRANCH_NAME }}

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Set up Python environment
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install gspread
          python3 -m pip install gspread_dataframe
          python3 -m pip install pandas
          python3 -m pip install python-frontmatter
          python3 -m pip install six

      - id: 'read_files'
        uses: Ana06/get-changed-files@v2.0.0

      - name: iterate over pull request files
        env:
          INPUT_SHEET_ID: '1bdyhGrj0oNz-_qW3Rv2GNGqhZZ73rgj-DYWePLA_1Ms'
          INPUT_SHEET_TITLE: 'Open_Patent_Datasets'
          INPUT_CREDS: ${{ secrets.GSHEET_CREDENTIALS }}
          INPUT_TEMPDIR: 'index_archive'
        run: |
          git status
          for added_file in ${{ steps.read_files.outputs.added }}; do
            if [ "${added_file: -3}" == ".md" ]
            then
              echo "this is a markdown file ${added_file}"
              python3 scripts/submit_dataset.py ${added_file}
              echo "::set-output name=commit_files::true"
            fi
          done

      - name: Commit files
        if: steps.check_diff.outputs.commit_files == 'true'
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add index_archive/*.csv datasets/*.md
            git commit -m "added uuid to file, updated CSV (#${{ github.event.number }})"
            git push --set-upstream origin ${{ env.BRANCH_NAME }}

      - name: Commit merge
        run: |
            git fetch
            git checkout main
            git pull origin ${{ env.BRANCH_NAME }}
            git pull
            git push
